  ```yaml
   name: Build Windows Installer

   on:
     push:
       branches: [ main ] # Or your default branch, e.g., master
     workflow_dispatch: # Allows manual triggering from the Actions tab

   jobs:
     build:
       runs-on: windows-latest # Use a Windows runner for MSI

       steps:
       - name: Checkout repository
         uses: actions/checkout@v4 # Latest version might change

       - name: Set up Python
         uses: actions/setup-python@v4 # Latest version might change
         with:
           python-version: '3.9' # Choose a Python version you use for development

       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt

       - name: Build MSI installer with cx_Freeze
         run: python setup.py bdist_msi

       - name: Upload MSI Artifact
         uses: actions/upload-artifact@v4 # Latest version might change
         with:
           name: SteamDL-Installer-MSI
           path: dist/*.msi # Path to where cx_Freeze outputs the MSI
                            # (cx_Freeze usually puts it in build/exe.win-amd64-3.9/ or dist/)
                            # Your setup.py specifies "build_exe": "dist/steamdl", so MSI might be in 'dist/' directly or a subdir.
                            # Adjust 'path:' if your MSI is located elsewhere after the build.
                            # For bdist_msi, it's typically 'dist/*.msi'.
   ```
